### ISSUE TITLE
bug in migration of responses

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#70]
chokes on some data:
```
(node:9134) UnhandledPromiseRejectionWarning: error: malformed array literal: "[{"name":"primary_health_care","value":"primary_health_care","open_date":null,"deployment_scale":null,"notes":null},{"name":"secondary_health_care","value":"secondary_health_care","open_date":null,"deployment_scale":null,"notes":null},{"name":"mental_health","value":"mental_health","open_date":null,"deployment_scale":null,"notes":null},{"name":"sexual_reproductive_health","value":"sexual_reproductive_health","open_date":null,"deployment_scale":null,"notes":null}]"
    at Connection.parseE (/home/ec2-user/msf-reach-schema/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/home/ec2-user/msf-reach-schema/node_modules/pg/lib/connection.js:380:19)
    at TLSSocket.<anonymous> (/home/ec2-user/msf-reach-schema/node_modules/pg/lib/connection.js:120:22)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by matthewberryman** [comment]
fixed in https://github.com/MSFREACH/msf-reach-schema/commit/2387193e61445e257daf3e4d434dc22d3d7f47f2
